version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: menu-mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
